module.exports = name => {

    if(name === "Man Utd") return "Manchester United";
    if(name === "Man City") return "Manchester City";
    if(name === "Stoke") return "Stoke City";
    if(name === "West Brom") return "West Bromwich";
    if(name === "Leicester") return "Leicester City";
    if(name === "Celta") return "Celta Vigo";
    if(name === "VfB Stuttgart") return "Stuttgart";
    if(name === "AS Roma") return "Roma";
    if(name === "Inter Milan") return "Inter";
    if(name === "AC Milan") return "Milan";
    if(name === "Huddersfield Town") return "Huddersfield";
    if(name === "Dortmund") return "Borussia Dortmund";
    if(name === "Hertha Berlin") return "Hertha";
    if(name === "C Palace") return "Crystal Palace";
    if(name === "RB Leipzig") return "Leipzig";
    if(name === "Spal") return "SPAL";
    if(name === "Arsenal FC") return "Arsenal";
    if(name === "Tottenham Hotspur") return "Tottenham";
    if(name === "Deportivo La Coruna") return "Deportivo";
    if(name === "Borussia M&apos;gladbach") return "Borussia Mönchengladbach";
    if(name === "M'gladbach") return "Borussia Mönchengladbach";
    if(name === "Mgladbach") return "Borussia Mönchengladbach";
    if(name === "Amiens SC") return "Amiens";
    if(name === "St Etienne") return "Saint-Etienne";
    if(name === "ESTAC Troyes") return "Troyes";
    if(name === "Hellas Verona") return "Verona";
    if(name === "AS Monaco") return "Monaco";
    if(name === "Sporting Lisbon") return "Sporting";
    if(name === "Sporting CP") return "Sporting";
    if(name === "RB Salzburg") return "Salzburg";
    if(name === "Hannover 96") return "Hannover";
    if(name === "Swansea City") return "Swansea";
    if(name === "Mainz 05") return "Mainz";
    if(name === "Schalke 04") return "Schalke";
    if(name === "FC Koln") return "Koln";
    if(name === "Eintracht Frankfurt") return "Eintracht";
    if(name === "Sociedad") return "Real Sociedad";
    if(name === "Real Betis") return "Betis";

    return name;
};
