module.exports = name => {

    if(name === "Man Utd") return "Manchester United";
    if(name === "Man City") return "Manchester City";
    if(name === "Stoke") return "Stoke City";
    if(name === "West Brom") return "West Bromwich";
    if(name === "West Bromwich Albion") return "West Bromwich";
    if(name === "West Ham United") return "West Ham";
    if(name === "Leicester City") return "Leicester";
    if(name === "Celta") return "Celta Vigo";
    if(name === "VfB Stuttgart") return "Stuttgart";
    if(name === "AS Roma") return "Roma";
    if(name === "Inter Milan") return "Inter";
    if(name === "AC Milan") return "Milan";
    if(name === "Huddersfield Town") return "Huddersfield";
    if(name === "Dortmund") return "Borussia Dortmund";
    if(name === "Hertha Berlin") return "Hertha";
    if(name === "C Palace") return "Crystal Palace";
    if(name === "RB Leipzig") return "Leipzig";
    if(name === "Spal") return "SPAL";
    if(name === "Arsenal FC") return "Arsenal";
    if(name === "Tottenham Hotspur") return "Tottenham";
    if(name === "Deportivo La Coruna") return "Deportivo";
    if(name === "Deportivo La Coruña") return "Deportivo";
    if(name === "Borussia M&apos;gladbach") return "Borussia Mönchengladbach";
    if(name === "M'gladbach") return "Borussia Mönchengladbach";
    if(name === "Mgladbach") return "Borussia Mönchengladbach";
    if(name === "Amiens SC") return "Amiens";
    if(name === "St Etienne") return "Saint-Etienne";
    if(name === "St. Etienne") return "Saint-Etienne";
    if(name === "Saint-Étienne") return "Saint-Etienne";
    if(name === "ESTAC Troyes") return "Troyes";
    if(name === "Hellas Verona") return "Verona";
    if(name === "AS Monaco") return "Monaco";
    if(name === "Sporting Lisbon") return "Sporting";
    if(name === "Sporting CP") return "Sporting";
    if(name === "RB Salzburg") return "Salzburg";
    if(name === "FC Red Bull Salzburg") return "Salzburg";
    if(name === "Hannover 96") return "Hannover";
    if(name === "Swansea City") return "Swansea";
    if(name === "Mainz 05") return "Mainz";
    if(name === "FSV Mainz 05") return "Mainz";
    if(name === "Schalke 04") return "Schalke";
    if(name === "FC Schalke 04") return "Schalke";
    if(name === "FC Koln") return "Koln";
    if(name === "1. FC Köln") return "Koln";
    if(name === "Cologne") return "Koln";
    if(name === "Eintracht Frankfurt") return "Eintracht";
    if(name === "Frankfurt") return "Eintracht";
    if(name === "Sociedad") return "Real Sociedad";
    if(name === "Real Betis") return "Betis";
    if(name === "Paris St-G") return "PSG";
    if(name === "Paris Saint Germain") return "PSG";
    if(name === "Paris Saint-Germain") return "PSG";
    if(name === "TSG Hoffenheim") return "Hoffenheim";
    if(name === "1899 Hoffenheim") return "Hoffenheim";
    if(name === "SC Freiburg") return "Freiburg";
    if(name === "VfL Wolfsburg") return "Wolfsburg";
    if(name === "FC Augsburg") return "Augsburg";
    if(name === "Brighton & Hove Albion") return "Brighton";
    if(name === "AFC Bournemouth") return "Bournemouth";
    if(name === "Bayer 04 Leverkusen") return "Bayer Leverkusen";
    if(name === "Leverkusen") return "Bayer Leverkusen";
    if(name === "Hamburg SV") return "Hamburg";
    if(name === "Newcastle United") return "Newcastle";
    if(name === "Wolverhampton Wanderers") return "Wolverhampton";
    if(name === "Wolves") return "Wolverhampton";
    if(name === "Alavés") return "Alaves";
    if(name === "Cardiff City") return "Cardiff";
    if(name === "1. FC Nuremberg") return "Nurnberg";
    if(name === "1. FC Nürnberg") return "Nurnberg";
    if(name === "Fortuna Dusseldorf") return "Fortuna";
    if(name === "Lok. Moscow") return "Lokomotiv";
    if(name === "Lokomotiv Moscow") return "Lokomotiv";
    if(name === "PSV Eindhoven") return "PSV";
    if(name === "Vik. Plzen") return "Viktoria Plzen";
    if(name === "Plzen") return "Viktoria Plzen";
    if(name === "SL Benfica") return "Benfica";
    if(name === "Crvena Zvezda") return "Red Star Belgrade";
    if(name === "FC Porto") return "Porto";
    if(name === "Shakhtar") return "Shakhtar Donetsk";
    if(name === "Akhisar Bld") return "Akhisarspor";
    if(name === "Akhisar") return "Akhisarspor";
    if(name === "BATE Borisov") return "BATE";
    if(name === "Rapid Wien") return "Rapid Vienna";
    if(name === "MOL Vidi FC") return "Vidi";
    if(name === "MOL Vidi") return "Vidi";
    if(name === "PAOK Salonika") return "PAOK";
    if(name === "Vorskla") return "Vorskla Poltava";
    if(name === "FK Qarabag") return "Qarabag";
    if(name === "Qarabag FK") return "Qarabag";
    if(name === "Zenit St Petersburg") return "Zenit";
    if(name === "Fenerbahçe") return "Fenerbahce";
    if(name === "RSC Anderlecht") return "Anderlecht";
    if(name === "Dynamo Kyiv") return "Dynamo Kiev";
    if(name === "FK Jablonec") return "Jablonec";
    if(name === "FC Astana") return "Astana";
    if(name === "FC Copenhagen") return "Copenhagen";
    if(name === "KRC Genk") return "Genk";
    if(name === "Malmo FF") return "Malmo";
    if(name === "Malmö FF") return "Malmo";
    if(name === "Sarpsborg 08") return "Sarpsborg";
    if(name === "Ludogorets Razgrad") return "Ludogorets";
    if(name === "FC Zurich") return "Zurich";
    if(name === "Zürich") return "Zurich";
    if(name === "Dynamo Zagreb") return "Dinamo Zagreb";
    if(name === "Sp. Trnava") return "Spartak Trnava";
    if(name === "F91 Dudelange") return "Dudelange";
    if(name === "Olympiakos") return "Olympiacos";
    if(name === "Olympiacos Piraeus") return "Olympiacos";
    if(name === "FC Krasnodar") return "Krasnodar";
    if(name === "Vallecano") return "Rayo Vallecano";
    if(name === "FK Krasnodar") return "Krasnodar";

    if(name === "Atlético Madrid") return "Atletico Madrid";
    if(name === "Leganés") return "Leganes";


    return name;
};
